name: "tag-auto-release"
on:
  push:
    tags:
      - "v*"

jobs:
  build_windows:
    name: Build On Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Cargo Index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Cargo Build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-windows
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-fqlink-binaries
          path: |
            target/release/fqlink.exe

  build_x86_64-linux-musl:
    name: Build On x86_64-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Cargo Index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Cargo Build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-x86_64-linux-musl
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
          override: true
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cross
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target x86_64-unknown-linux-musl
      - name: Upload x86_64-linux-musl Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: x86_64-linux-musl-fqlink-binaries
          path: |
            target/x86_64-unknown-linux-musl/release/fqlink

  build_aarch64-linux-musl:
    name: Build On aarch64-linux-musl
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache Cargo Registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Cargo Index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/index
          key: ${{ runner.os }}-cargo-index-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache Cargo Build
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-${{ hashFiles('**/Cargo.lock') }}-aarch64-linux-musl
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: aarch64-unknown-linux-musl
          override: true
      - uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: cross
      - uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --release --target aarch64-unknown-linux-musl
      - name: Upload aarch64-linux-musl Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: aarch64-linux-musl-fqlink-binaries
          path: |
            target/aarch64-unknown-linux-musl/release/fqlink

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [build_windows, build_x86_64-linux-musl, build_aarch64-linux-musl]
    steps:
      - name: Download Windows Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: windows-fqlink-binaries
          path: ./windows-fqlink-binaries
      - name: Download x86_64-linux-musl Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: x86_64-linux-musl-fqlink-binaries
          path: ./x86_64-linux-musl-fqlink-binaries
      - name: Download aarch64-linux-musl Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: aarch64-linux-musl-fqlink-binaries
          path: ./aarch64-linux-musl-fqlink-binaries
      # ls downloaded files
      - name: List Downloaded Artifacts
        run: |
          ls -lhaR
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload Windows Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./windows-fqlink-binaries/fqlink.exe
          asset_name: fqlink-windows.exe
          asset_content_type: application/octet-stream

      - name: Upload x86_64-linux-musl Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./x86_64-linux-musl-fqlink-binaries/fqlink
          asset_name: fqlink-x86_64-linux-musl
          asset_content_type: application/octet-stream

      - name: Upload aarch64-linux-musl Server Build to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./aarch64-linux-musl-fqlink-binaries/fqlink
          asset_name: fqlink-aarch64-linux-musl
          asset_content_type: application/octet-stream
